---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: core-cluster-networking
value: 1900000
globalDefault: false
preemptionPolicy: Never
description: "This priority class should be used for core networking pods only"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: core-cluster-storage
value: 1800000
globalDefault: false
preemptionPolicy: Never
description: "This priority class should be used for core networking pods only"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: core-cluster-operators
value: 1700000
globalDefault: false
preemptionPolicy: Never
description: "This priority class should be used for core networking pods only"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: default
value: 100000
globalDefault: true
description: "This priority class is for standard applications"

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: legacy-applications
value: 70000
globalDefault: false
description: "This priority class is for legacy applications"

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: data-science-workers
value: 40000
globalDefault: false
description: "This priority class is for data science applications"

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: spot-instances
value: 10000
globalDefault: false
description: "This priority class is for pods that are only to use spare capacity"