apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-challenge-1
  namespace: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scheduling-challenge-1
  template:
    metadata:
      labels:
        name: scheduling-challenge-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2