apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-server
  template:
    metadata:
      labels:
        name: web-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2
        
