apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-certs-config
data:
  certs.toml: |
    [tls.stores]
      [tls.stores.default]
        [tls.stores.default.defaultCertificate]
          certFile = "/certs/tls.crt"
          keyFile  = "/certs/tls.key"

    [tls.options]
      [tls.options.default]
        [tls.options.default.clientAuth]
          # in PEM format. each file can contain multiple CAs.
          caFiles = ["/certs/ca.crt"]
          clientAuthType = "VerifyClientCertIfGiven"

---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-certs
data:
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRREpNdE5Hb3dSMFlITE8KeGk4WlY1YkJJNGc4Wm1BOUkvSDl6
    WmhGS3o4WjR1elNmY1kvWUJPdHZzZGtTUDRVRmdjZ1lZWVJvM0R1QnQ5TgpFYXJLbGlURTI0cTdE
    enBqbENqeGpUWVNMSTNLOE5Mdk5oRVB6VzNTR1djUlhZZmoyV25NM2RZWFJub3lQS0FRCmZ6SjNV
    R0dja1lRS3FvanE0SEdvUEJlU3d3MnVrR0ZmbmxsblVTV0xESEJiVURUU2NtUEwra08wdDZxQTR6
    NSsKSkRoeDE4cEtQY3ZrQ2s1ZitVelhYR1JCVUJqdHdtaytKRUxCTGxMNVVUZG41VCt5dHduaFdz
    ZlJRcW4wanY0cQo0QzhKNTdHTjNzTmY5eDhMVTlqVm9UUlNPMWJWVnhaWklNdFRVS3I4NThIMnlK
    YWZmWHowcE9iNklpR3JMT3ZZCjVWRXNFOHBUQWdNQkFBRUNnZ0VBT2Z1cXhiV2ZTQWF2cjRXUDkw
    YTF6STEzNnFnNlhnUm83aEw5S2hudmduOVMKYnNzT2doOG5MTEJKZUU1TTR1OENPTVBDUm4wS3c1
    NDVabFdNR2Z3eE5vWnFzY1FPdUxudkhzWHFha3hxeEt5bwpyWVd3WHhSOTdNbWpXVzdTQmNrWFk1
    SWU2L0JFc1F1bHVYdGV5T0hpYjZQRUlPcktzSjNrUTI2bUFJYXovN1ZiClk5QnEyL2VSYmdvT21q
    TGY1RHROUk1yTXdUcjN5V1llVVduWE4zaDNqTDEwcEkxSDcya1FpbTF6STBybTNWZHgKMTRpa0Zk
    cTRkWUhuK0VtQ3VIRTBrTThybVVzak5QU1grTTh5Zm5PU3B5RWx5My9xRGVYcVhDNklVY1k5TXpp
    QgozMnk3TUMxM1UrT2VJRjNNVzlsZlVwQTBCWHhSUVBKZWFFQ29obTNXZVFLQmdRRHJpUXRUNnRG
    WS9iMENIUnRTCjdKcFVoZ1BPa3ZIRjk1RVlKbFI1MVFuWk9NUlhmNS9MQVM4a2UwL1dncmUzQzJw
    QnNVUnROc3QyRVlSNTQ4REkKQmtuREdUYTJBR0d5bDZXRk15cUdPYkFQY2M2d25rVldpVGNhSkxh
    ZmJ1YnQ1ZDB6MDV1VHZWR1FoMDBYU2s3Ugp4bXIxdTlZQVd6SmJNWUFxSS9ISDN1THdqd0tCZ1FE
    YXJnazRKYWFxMlFnU2RxQnJ4VXdvc3lzMEZaNWF4M1NBCkRUdk44QzVremp0REtiYWtHNnMydjJB
    RGJTa1YvWWV6VW82bUtWMytIN3ZBRTBocDBscFFYVTg4Q0FIMjFVTm8KQVhkbWdxK1M1R1hpOUpU
    TDhLWGlQaUJmTG9WNkQ5V05JV0w0ZmUzQ3REMURpZy8wU3ZJWEorWWNoODd6U0Q5WApjai91YmMr
    ai9RS0JnUURDdjNHcVZVSDd2dkdFeWVSSjBIQmE2dVJDN2FVUzl2djFaOXY1VUhqd0xzdkpQVEUy
    CmZTZ3BsZndSZGN2SmdacTk3b0NSZlBrR0NyM3F1ckl2c1dOVCtZa1BPNG1NVFc4Q2o2ZmRpOTFU
    SjlxcWxuTG0KZGxZbE82MzBiWkpycWVBWWRpTHhLVnhEa0Z2aG9nTkIyRG1nTFV0b3gvNy9BQkxr
    eFF1cEkxV3BhUUtCZ1FDTQo2c21XSE8waCsybHdQSEYwQVZmcWdrcTg3WkYxL2tIY29xcC9NdDh5
    cHBNWjNLK05ZU2NieUljZXJpRmp3bFRJCkFkTmEwQjE1dlFsSDVTVXN6QmpXNE1wR2JRS1hCU2JD
    eHU4aVorU3NTL0k4SmxBY2U1N3FCQTdvUnhwTVpoZS8KTWx5TXRObWFObnVrSWp2VnVOWDRoZ1dM
    TFJqM1BQOVVZcE5BR2hOTUlRS0JnRXJzOU9USmVWUHZWVHNhTE9TTQpjODdTNkt3ZVdnVENqRm9I
    YXdmeSsrdzIyUlc0cjVpUFhScFRMTlJwdzBFaXNkUHRZVnd6UVlxR0RwMlFybWh3CnhzSHVHVlYv
    SjBvMEoxNm1ZV2NaNElZOFBCTnZ1RElQS2xTUmorZjFuY2c3YjhsNVBLZzFQa3hLZzdmUllJblIK
    cndESVlWVHkvWEpnUGxRUzJjUlVOK0RVCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPakNDQWlJQ0ZDWHNSOTlFcnJ1TU5uTXZi
    ZCsyc3BVYnRNRzdNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1GY3gKQ3pBSkJnTlZCQVlUQWtGVk1STXdF
    UVlEVlFRSURBcFRiMjFsTFZOMFlYUmxNU0V3SHdZRFZRUUtEQmhKYm5SbApjbTVsZENCWGFXUm5h
    WFJ6SUZCMGVTQk1kR1F4RURBT0JnTlZCQU1NQjFKTE9ITXRRMEV3SGhjTk1qQXhNREk1Ck1UY3dN
    REV4V2hjTk1qRXhNREk1TVRjd01ERXhXakJjTVFzd0NRWURWUVFHRXdKQlZURVRNQkVHQTFVRUNB
    d0sKVTI5dFpTMVRkR0YwWlRFaE1COEdBMVVFQ2d3WVNXNTBaWEp1WlhRZ1YybGtaMmwwY3lCUWRI
    a2dUSFJrTVJVdwpFd1lEVlFRRERBeFNTemh6TFZSeVlXVm1hV3N3Z2dFaU1BMEdDU3FHU0liM0RR
    RUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURKTXROR293UjBZSExPeGk4WlY1YkJJNGc4Wm1BOUkv
    SDl6WmhGS3o4WjR1elNmY1kvWUJPdHZzZGsKU1A0VUZnY2dZWVlSbzNEdUJ0OU5FYXJLbGlURTI0
    cTdEenBqbENqeGpUWVNMSTNLOE5Mdk5oRVB6VzNTR1djUgpYWWZqMlduTTNkWVhSbm95UEtBUWZ6
    SjNVR0dja1lRS3FvanE0SEdvUEJlU3d3MnVrR0ZmbmxsblVTV0xESEJiClVEVFNjbVBMK2tPMHQ2
    cUE0ejUrSkRoeDE4cEtQY3ZrQ2s1ZitVelhYR1JCVUJqdHdtaytKRUxCTGxMNVVUZG4KNVQreXR3
    bmhXc2ZSUXFuMGp2NHE0QzhKNTdHTjNzTmY5eDhMVTlqVm9UUlNPMWJWVnhaWklNdFRVS3I4NThI
    Mgp5SmFmZlh6MHBPYjZJaUdyTE92WTVWRXNFOHBUQWdNQkFBRXdEUVlKS29aSWh2Y05BUUVMQlFB
    RGdnRUJBR1dmCjdxem1YZUFDQkt4VDl3aklmRHNFT1p5OE9iNFhCL2JOMXZEWDdhK0JmY0lTQnlh
    NVpXYS9FQUJuMzk1RWVKd3kKVFFYdjFuVlROU3lMSEZJc3paSE1naE1ISHAycjluR0dHakxaeVFv
    VU1VVUVaMXJ1L0c3VzVza2JoRm1oNE9tRQp3UlJtekpacExGSitPV3lTRVZTdTJvUUR1dEU4NGxu
    bG0vdXRKT0dXK1llaEQwSVR4cHpEY3hJb3k5Yi9XNTYzCnJJUDdhNXBiTEMvaTBmNmkxRzIxTStG
    RGNLV2FwK3QwakhyUk80SjZUYTJmd3IwZzdqQk53TkJyb2VMeHJkTVMKTlE1Y1hGYXpGMUJwWUY3
    OU12Rk1sYWIzZDRJZGNqZmowUUZOdjkvQ2pxbWJYc2UvbGhaN3htR2lseHkvV25qRQpYS2lrOW15
    cmJ1MzlUWFd1dE1ZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqekNDQW5lZ0F3SUJBZ0lVVXFuaXNRYzZn
    bEVMU2hCTm9qcDEveENJUjdnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1Z6RUxNQWtHQTFVRUJoTUNR
    VlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJ
    RmRwWkdkcGRITWdVSFI1SUV4MFpERVFNQTRHQTFVRUF3d0hVa3M0Y3kxRFFUQWVGdzB5Ck1ERXdN
    amt4TlRJNE5URmFGdzB5TXpBNE1Ua3hOVEk0TlRGYU1GY3hDekFKQmdOVkJBWVRBa0ZWTVJNd0VR
    WUQKVlFRSURBcFRiMjFsTFZOMFlYUmxNU0V3SHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFY
    UnpJRkIwZVNCTQpkR1F4RURBT0JnTlZCQU1NQjFKTE9ITXRRMEV3Z2dFaU1BMEdDU3FHU0liM0RR
    RUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURWZXFmZ2VEaEsvUDdwRVZQZkNyaUZTbjFtY1JrQzJk
    MkRJalRGUC9IdStVRmYyNlkxNkR4MTZEdlkKVHlDT2oxUUI4MGxHd0hwRVVNQy8zSFJyMHhvbklT
    czkwQTk3TWVIVUJJc01ZZy8yYU1NUVdNMkRLaVI0RmdIcQpqdldWQTlwU3FDQTB2U0RHZEJRbnZw
    TmVyWWRUWDBudUZQdnR4Q09EU2pXMVhaZzczSXAzWTZTRTRqYVZhN25OCi92cFBYdTZ3S05MSmU2
    cjZLWERUZThKUXZ2L2Zqd1Z5ZlRKeWxCQklxeWRVVnRtNTVabXhVV2kyOUdwK1hKYnMKcTN1b2RZ
    ZXYyZWtVbTNCbzdFUGFLeVY5Nld5elVMVGFDTEpZTnhnTHVhVyt3R2NybGYzeTIvY3ZDTDI3TXln
    cwp1alhZVzVJZ0ZoWEU0WGVKZTRKNzdyaVNqMHJmQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJT
    TG5SazlxeDFXCjVrZEhXZDlzOWZTVFZMOHg0ekFmQmdOVkhTTUVHREFXZ0JTTG5SazlxeDFXNWtk
    SFdkOXM5ZlNUVkw4eDR6QVAKQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dV
    QUE0SUJBUUIwRDhsR0xIQWo2bGNCSEJwSAo3dWVpWDlQWnVOdXV4UkNPRnRYb2F4b09DemhvS05h
    KytwWTlNdzA1QXgzamlobERQTlZwMWgvV1BVYndxYldHClVuVjU5UXRsbzA2dURPOCtVTFExMi8z
    bVEwYWlyN0R1Mkc3ZXdkampMcFhMQ0RIaVVNakZySThaa002c1pkVnIKVkVXaUd2VjlLSERIcUYw
    M1FTbTFvTlpyRmFxTUlrc1k0S0F2WWl1T1ZVNXdKakt5N2F2SFBoZE1HOUZrNFIxSwozQkprbTZz
    TFppRHdMQzM0UWtPZG50MXRCTEE3bm5qL1ZFZHFQSmhvWC90clpTK3ovc3VNZlZiYTFoMzBaclZU
    Cmw2SzZRTmRPSCs0cUU4dkp1aWYzSGhzak93Y1RHRWlqRmJpczhLR1dxVHRBbHU3KzhtalNUdU05
    Qmg5aFQ4NVoKTmIvNwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

---