---
apiVersion: v1
kind: Namespace
metadata:
  name: bob
  labels:
    type: user

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage
  namespace: bob
spec:
  hard:
    ceph-block-ssd.storageclass.storage.k8s.io/requests.storage: 200Gi
    ceph-block-hdd.storageclass.storage.k8s.io/requests.storage: 1Ti

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: network
  namespace: bob
spec:
  hard:
    services.nodeports: "0"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: priority-class
  namespace: bob
spec:
  hard:
    pods: "0"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: 
        - system-node-critical
        - system-cluster-critical
        - core-cluster-networking
        - core-cluster-storage
        - core-cluster-operators

---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: bob
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: "1"
      nvidia.com/gpu: "0"
    defaultRequest:
      memory: 256Mi
      cpu: "0.5"
      nvidia.com/gpu: "0"
    type: Container
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: bob
spec:
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:          # Apply this policy to all pods in the namespace
  ingress:
  - from:
    - podSelector: {}     # Allow traffic from other pods in the same namespace
    - namespaceSelector:  # All traffic from namespaces with the following labels
        matchLabels:
          type: system
  policyTypes:
  - Ingress               # Deny all Ingress traffic that does not match the above rules.
