---
apiVersion: v1
kind: Namespace
metadata:
  name: alice

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage
  namespace: alice
spec:
  hard:
    ceph-block-ssd.storageclass.storage.k8s.io/requests.storage: 200Gi
    ceph-block-hdd.storageclass.storage.k8s.io/requests.storage: 1Ti

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: network
  namespace: alice
spec:
  hard:
    services.nodeports: 0

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: priority-class
  namespace: alice
spec:
  hard:
    pods: "0"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: 
        - system-node-critical
        - system-cluster-critical
        - core-cluster-networking
        - core-cluster-storage
        - core-cluster-operators

---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: alice
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: "1"
      nvidia.com/gpu: 0
    defaultRequest:
      memory: 256Mi
      cpu: "0.5"
      nvidia.com/gpu: 0
    type: Container
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: alice
spec:
  podSelector: {}
  policyTypes:
  - Ingress
