---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-resources-ryan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-resources
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ryan