---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage
  namespace: web-server
spec:
  hard:
    ceph-block-ssd.storageclass.storage.k8s.io/requests.storage: 10Gi
    ceph-block-hdd.storageclass.storage.k8s.io/requests.storage: 100Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: network
  namespace: web-server
spec:
  hard:
    services.nodeports: "0"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: priority-class
  namespace: web-server
spec:
  hard:
    pods: "0"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: 
        - system-node-critical
        - system-cluster-critical
        - core-cluster-networking
        - core-cluster-storage
        - core-cluster-operators