apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: web-server
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: "1"
      nvidia.com/gpu: "0"
    defaultRequest:
      memory: 256Mi
      cpu: "0.5"
      nvidia.com/gpu: "0"
    type: Container